# 파일 규격 버전
version: "3"
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services:
  # 서비스 명
  mongodb:
    # 사용할 이미지
    image: mongo
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너 이름 설정
    container_name: airnameDB
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "27018:27017"
    # -e 옵션
    volumes:
      # -v 옵션 (다렉토리 마운트 설정)
      - /data/mongodb/data/db:/data/db
  web:
    build:
      context: ./backend_django
      dockerfile: Dockerfile
    command: gunicorn YourName.wsgi:application --bind 0.0.0.0:8000
    container_name: django
    volumes:
      - "/volume/django"
    ports:
      - "8000:8000"
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /volume/nginx:/etc/nginx/conf.d
  #     - /volume/django/.static_root/:/static
  #   depends_on:
  #     - web
